In [3]:
import libraries as lb

In [5]:
consumption_data = lb.pd.read_csv('dataset/consumption_facility_cleaned.csv')
consumption_data.head()

,Patient_ID,Region,Medicine_ID,DrugName,Daily_Consumption_Units,Out_of_Stock_Days,Wastage_Units,Bed_Days,Supplies_Used,Total_Consumption,Stockout_Flag,Wastage_Flag,Consumption_per_Bed
0,P001,Indore,M07208F17,LIGNOCAINE HYDROCHLORIDE 2% INJ,0.5,0,0,2,"Gloves, IV",1.0,False,False,0.5
1,P001,Indore,M09598F70,ADRENALINE INJ 1ML,2.0,0,0,2,"Gloves, IV",4.0,False,False,2.0
2,P001,Indore,M359D09B5,LIQUID PARAFFIN 100ML,0.0,0,1,2,"Gloves, IV",0.0,False,True,0.0
3,P001,Indore,M524E5E35,ESOMEPRAZOLE 40MG,0.5,0,0,2,"Gloves, IV",1.0,False,False,0.5
4,P001,Indore,M589A5AA4,WATER FOR INJECTION 10ML SOLUTION,3.0,0,0,2,"Gloves, IV",6.0,False,False,3.0

In [6]:
demand_data=lb.pd.read_csv("dataset/demand_sales_cleaned.csv")
demand_data.head()

,Order_ID,Order_Date,Patient_ID,Dept,Specialisation,Medicine_ID,DrugName,Formulation,Quantity,ReturnQuantity,...,RtnMRP,Order_Status,Delivery_Date,Lead_Time_Days,Delivered_Flag,Delivery_Delay,Return_Percentage,Profit,Order_Month,Lead_Time_Final
0,O00001,2024-06-01,P045,Department1,Specialisation6,M1CA76D1B,ZINC ACETATE 20MG/5ML SYP,Form1,1,0,...,0.0,Cancelled,NaN,0,False,NaN,0.0,3.85,2024-06,0
1,O00002,2024-09-18,P387,Department1,Specialisation7,M318FBCBC,CEFTAZIDIME 2GM+AVIBACTAM 500MG,Form1,1,0,...,0.0,Delivered,2024-09-27,9,True,9.0,0.0,182.16,2024-09,9
2,O00003,2024-11-03,P328,Department3,Specialisation2,M82D7852E,EPTIFIBATIDE 0.75MG/ML,Form2,1,0,...,0.0,Delivered,2024-11-06,3,True,3.0,0.0,3229.94,2024-11,3
3,O00004,2024-01-15,P220,Department1,Specialisation40,MCA6D8773,WATER FOR INJECTION 10ML SOLUTION,Form1,2,0,...,0.0,Cancelled,NaN,0,False,NaN,0.0,40.24,2024-01,0
4,O00005,2024-09-27,P217,Department1,Specialisation5,M18E1DD4A,LORAZEPAM 1MG,Form1,1,0,...,0.0,Delivered,2024-10-09,12,True,12.0,0.0,0.07,2024-09,12

In [7]:
inventory_stock_data=lb.pd.read_csv("dataset/inventory_stock_cleaned.csv")
inventory_stock_data.head()

,Medicine_ID,DrugName,Formulation,Category,Batch_No,Manufacture_Date,Expiry_Date,Current_Stock,Min_Required,Max_Capacity,...,Restock_Lead_Time_Days,Reorder_Level,Stock_Cover_Days,Vendor_ID,Expiry_Risk,Inventory_Gap,Stockout_Risk,Reorder_Flag,Overstock_Flag,Stock_per_Day
0,M07208F17,LIGNOCAINE HYDROCHLORIDE 2% INJ,Injection,Parenteral,BATCH1803,2023-02-21,2024-02-21,230,32,845,...,6,35,77,V923,True,198,False,False,False,76.666667
1,M09598F70,ADRENALINE INJ 1ML,Injection,Parenteral,BATCH7964,2023-08-12,2024-08-11,78,79,925,...,7,87,13,V775,True,-1,True,True,False,13.000000
2,M359D09B5,LIQUID PARAFFIN 100ML,Other,Other,BATCH6890,2023-06-24,2025-06-23,195,69,949,...,9,76,14,V307,False,126,False,False,False,13.928571
3,M524E5E35,ESOMEPRAZOLE 40MG,Other,Other,BATCH4949,2023-02-19,2025-02-18,260,43,381,...,3,47,37,V270,False,217,False,False,False,37.142857
4,M589A5AA4,WATER FOR INJECTION 10ML SOLUTION,Injection,Parenteral,BATCH4896,2023-03-03,2024-03-02,476,53,685,...,9,58,40,V711,True,423,False,False,False,39.666667

In [8]:
supplier_procurement_data=lb.pd.read_csv("dataset/supplier_procurement_cleaned.csv")
supplier_procurement_data.head()

,Supplier_ID,Supplier_Name,Region,Avg_Lead_Time_Days,Reliability_Score,Cost_Per_Item,Last_Order_Date,Next_Delivery_Date,On_Time_Delivery_Rate,Delay_Risk,Reliability_Level,Poor_Performance,Efficiency_Score,Delivery_Gap_Days
0,V923,Supplier_1,Delhi,12,4.2,116.21,2024-01-19,2024-01-31,75,True,High,False,6.250000,12
1,V775,Supplier_2,Delhi,9,4.6,113.26,2024-11-14,2024-11-23,73,False,High,True,8.111111,9
2,V307,Supplier_3,Pune,8,4.1,118.98,2024-09-18,2024-09-26,80,False,High,False,10.000000,8
3,V270,Supplier_4,Pune,9,3.8,103.85,2024-05-24,2024-06-02,71,False,Low,True,7.888889,9
4,V711,Supplier_5,Pune,12,4.4,112.12,2024-08-10,2024-08-22,71,True,High,True,5.916667,12